// Generated by go-rpcgen. Do not modify.

package somepackage

import (
	"net/rpc"
)

type ArithService struct {
	impl Arith
}

func NewArithService(impl Arith) *ArithService {
	return &ArithService{impl}
}

type pArithAddRequest struct {
	A, B int
}

type pArithAddResponse struct {
	Result int
}

func (s *ArithService) Add(request *pArithAddRequest, response *pArithAddResponse) (err error) {
	response.Result, err = s.impl.Add(request.A, request.B)
	return
}

type ArithClient struct {
	client  *rpc.Client
	service string
}

func NewArithClient(client *rpc.Client, service string) *ArithClient {
	return &ArithClient{client, service}
}

func (_c *ArithClient) Add(a, b int) (result int, err error) {
	request := &pArithAddRequest{a, b}
	response := &pArithAddResponse{}
	err = _c.client.Call(_c.service+".Add", request, response)
	return response.Result, err
}
