// Generated by go-rpcgen. Do not modify.

package arith

import (
	"net/rpc"
)

type ArithService struct {
	impl Arith
}

func NewArithService(impl Arith) *ArithService {
	return &ArithService{impl}
}

func RegisterArithService(impl Arith) error {
	return rpc.RegisterName("Arith", NewArithService(impl))
}

type pArithAddRequest struct {
	A, B int
}

type pArithAddResponse struct {
	Result int
}

func (s *ArithService) Add(request *pArithAddRequest, response *pArithAddResponse) (err error) {
	response.Result, err = s.impl.Add(request.A, request.B)
	return
}

type ArithClient struct {
	client  *rpc.Client
	service string
}

func NewArithClient(client *rpc.Client) *ArithClient {
	return &ArithClient{client, "Arith"}
}

func (_c *ArithClient) Close() error {
	return _c.client.Close()
}

func (_c *ArithClient) Add(a, b int) (result int, err error) {
	_request := &pArithAddRequest{a, b}
	_response := &pArithAddResponse{}
	err = _c.client.Call(_c.service+".Add", _request, _response)
	return _response.Result, err
}
